language: cpp

compiler:
  - gcc
  - clang

sudo: required
dist: xenial

matrix:
  allow_failures:
    - compiler: clang

install:
  - sudo apt-get install cmake g++ git liblog4cxx10-dev freeglut3 freeglut3-dev libglpk-dev python-dev python-opengl libxmu-dev libxi-dev libqt4-dev libqt4-opengl-dev libassimp-dev libgtest-dev

before_script:
  - echo $LD_LIBRARY_PATH
  - sudo ldconfig

script:
  - cd Cpp/Dependencies && make unpack-deps
  - cd KrisLibrary && cd ..
  - make deps && cd ../..
  - cmake . -DKLAMPT_COMPILE_TESTS:BOOL=True
  - make Klampt
  - make apps
  - make python
  - sudo make python-install
  - make python2
  - sudo make python2-install
  - env CTEST_OUTPUT_ON_FAILURE=1 make test


# safelist
branches:
  only:
  - master
  - 0.8.7
  - 0.8.6
  - 0.8.5
  - 0.8.3
  - 0.8.2
  - 0.8.1
  - 0.8.0
  - v0.7
  - travis

notifications:
  email:
    - hauser.kris@gmail.com
